[package]
name = "egui_sdl2_gl"
version = "0.14.0"
authors = ["Arjun Nair <arjunair@gmail.com>"]
edition = "2018"
description = "Backend for Egui to use with sdl2-rs and open gl"
homepage = "https://github.com/ArjunNair/egui_sdl2_gl"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ArjunNair/egui_sdl2_gl"
categories = ["gui", "graphics"]
keywords = ["sdl2", "opengl", "egui", "gui", "gamedev"]
include = ["**/*.rs", "Cargo.toml"]
build = "build.rs"

[dependencies.sdl2]
version = "0.34"
features = ["bundled"]

[dependencies]
gl = "0.14"
egui = "0.14"

[dependencies.copypasta]
version = "0.7"
optional = true

[features]
clipboard = ["copypasta"]

[dev-dependencies]
egui_demo_lib = "0.14"